// fe-nuxt/app/pages/create.vue
<template>
   <div>
      <h1 class="text-3xl font-bold mb-6 text-gray-800">
         Add New Expense
      </h1>

      <ExpenseForm :is-submitting="isSubmitting" @submit="handleAddExpense" />
   </div>
</template>

<script setup lang="ts">
import { isAxiosError } from 'axios';
const { $axios } = useNuxtApp();

const isSubmitting = ref(false)

const handleAddExpense = async (data: ExpenseFormData) => {
   if (isSubmitting.value) return
   isSubmitting.value = true

   try {
      await $axios.post('/api/expenses', data);

      console.log('Expense added successfully');
      await navigateTo('/');
   } catch (err) {
      console.error('Error adding expense:', err);

      if (isAxiosError<ValidationResponseData>(err)) {
         if (err.response?.status === 422 && err.response.data.errors) {
            const validationErrors = err.response.data.errors;
            const errorMessages = Object.values(validationErrors)
               .flat()
               .join('\n');
            console.error(`Validation failed:\n${errorMessages}`);
         } else {
            console.error('An error occurred. Please try again.');
         }
      } else {
         console.error('An unexpected error occurred.');
      }
   } finally {
      isSubmitting.value = false;
   }
};
</script>

// frontend/src/app/create/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import ExpenseForm from '@/components/ExpenseForm'
import axios from '@/lib/axios'
import type { AxiosError } from 'axios'
import type { ExpenseFormData, ValidationResponseData } from '@/types'

export default function CreateExpensePage() {
    const router = useRouter()
    const [isSubmitting, setIsSubmitting] = useState<boolean>(false)

    const handleAddExpense = async (data: ExpenseFormData) => {
        if (isSubmitting) return
        setIsSubmitting(true)

        try {
            await axios.post('/api/expenses', data)

            alert('Expense added successfully!')
            router.push('/')
        } catch (err) {
            const error = err as AxiosError<ValidationResponseData>
            console.error('Failed to add expense:', error)

            if (error.response?.status === 422 && error.response.data.errors) {
                const validationErrors = error.response.data.errors
                const errorMessages = Object.values(validationErrors)
                    .flat()
                    .join('\n')
                alert(`Validation failed:\n${errorMessages}`)
            } else {
                alert('An error occurred. Please try again.')
            }
        } finally {
            setIsSubmitting(false)
        }
    }

    return (
        <div>
            <h1 className="text-3xl font-bold mb-6 text-gray-800">
                Add New Expense
            </h1>
            <ExpenseForm
                onSubmit={handleAddExpense}
                isSubmitting={isSubmitting}
            />
        </div>
    )
}
